INSERT INTO STORE (STORE_NAME, STORE_ADDRESS, STATE_NAME, POSTCODE) VALUES ('Apple Valley Plaza', '2701 Ming Avenue Bakersfield', 'CA', '93304');
INSERT INTO STORE (STORE_NAME, STORE_ADDRESS, STATE_NAME, POSTCODE) VALUES ('Apple Palo Alto', '340 University Avenue Palo Alto', 'CA', '94301');
INSERT INTO STORE (STORE_NAME, STORE_ADDRESS, STATE_NAME, POSTCODE) VALUES ('Apple Union Square', '300 Post Street San Francisco', 'CA', '94108');
INSERT INTO STORE (STORE_NAME, STORE_ADDRESS, STATE_NAME, POSTCODE) VALUES ('Apple Oakridge', '925 Blossom Hill Road San Jose', 'CA', '95123');
INSERT INTO STORE (STORE_NAME, STORE_ADDRESS, STATE_NAME, POSTCODE) VALUES ('Apple Stoneridge Mall', 'One Stoneridge Mall Pleasanton', 'CA', '94588');

INSERT INTO USER (USER_NAME, FIRST_NAME, LAST_NAME) VALUES ('johns', 'John', 'Smith');
INSERT INTO USER (USER_NAME, FIRST_NAME, LAST_NAME) VALUES ('mikeLee', 'Mike', 'Lee');
INSERT INTO USER (USER_NAME, FIRST_NAME, LAST_NAME) VALUES ('sean1990', 'Sean', 'Chang');

INSERT INTO USER_STORE (USER_ID, STORE_ID) VALUES (1, 1);
INSERT INTO USER_STORE (USER_ID, STORE_ID) VALUES (1, 2);
INSERT INTO USER_STORE (USER_ID, STORE_ID) VALUES (2, 4);
INSERT INTO USER_STORE (USER_ID, STORE_ID) VALUES (3, 5);